name: Issue cleanup
on:
  schedule:
    - cron: '0 1 * * *' # At 01:00, everyday
jobs:
  triage_issues:
    name: Issue triage
    runs-on: ubuntu-latest
    steps:
      - name: Find old issues and mark them stale
        uses: Krizzu/issue-triage-action@v1.0.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          staleAfter: 7
          closeAfter: 14
          staleLabel: "STALE 📺"
          staleComment: "This issue is %DAYS_OLD% days old, marking as stale! cc: @%AUTHOR%"
          closeComment: "Issue last updated %DAYS_OLD% days ago! Closing down!"
          showLogs: true